### PR TITLE
Add vercel analytics

### PR DESCRIPTION
**Pull request by magland**
See https://vercel.com/docs/analytics

Importantly, it only stores anonymized data and [does not use cookies](https://vercel.com/docs/analytics#how-visitors-are-determined)

This will help us see the number of unique visitors per day, their browser, their OS, their Country. But note that these pieces of data are not stored jointly... so we just get aggregated plots.

### CODE REVIEW

**Comment by WardBrian** [comment]
I don't have a particularly strong feeling either way with this, but I just want to ask (maybe a stupid question), does this cause any problems if we have users in the EU or covered by other data protection laws?

**Comment by magland** [comment]
According to this, we don't need to worry about it for Vercel
https://posthog.com/blog/best-gdpr-compliant-analytics-tools

**Comment by magland** [comment]
Do you have an opinion about this @jsoules ?

**Comment by jsoules** [comment]
Not a strong one. I've used Google Analytics in the past, but that does involve cookies and opt-in for GDPR areas. I don't particularly relish being more tightly bound to the Vercel ecosystem, but I suppose it's easy enough to back out later if we decide that's what's best.

So yeah, I think this is a good idea.

**Pull request merged**
