### PR TITLE
hide syntax error window by default

### PR DESCRIPTION
**Pull request by magland**
This replaces #51. Same functionality. Was just easier to start from scratch rather than resolve the conflicts caused by the other PRs.

### CODE REVIEW

**Comment by WardBrian** [comment]
What does this do with warnings?

a good example is to name a variable “jacobian”. This is going to be a reserved word in a future version of Stan, so for now it gives a compiler warning

**Comment by magland** [comment]
> What does this do with warnings?
> 
> a good example is to name a variable “jacobian”. This is going to be a reserved word in a future version of Stan, so for now it gives a compiler warning

Good point. Added a button for "Syntax warning"

image

**Comment by magland** [comment]
@WardBrian @jsoules is this okay to merge?

**Review by jsoules — COMMENTED** [review]
Perhaps dark orange might be a more appropriate (but still contrasting) color for warnings than blue?

Otherwise this seems fine to me if it's okay with you, @WardBrian

**Comment by WardBrian** [comment]
Yep, this is fine by me!

I think we may eventually be able to replace this with something built in to the Monaco editor for showing errors (see #76 and https://github.com/WardBrian/vscode-stan-extension), but this is definitely an improvement over the current behavior

**Pull request merged**
